MindMapWebApp/Models/ErrorViewModel.cs
using System;

namespace MindMapWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MindMapWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MindMapWebApp.Models;

namespace MindMapWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "This is a learning application for refreshing / gearing up on ASP .NET Core, MVC, Web API, etc.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Please don't contact me about this app; it's not worth either of our time.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MindMapWebApp/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MindMapClasses.Models;
using MindMapClasses.Services;
using MindMapWebApp.Services;

namespace MindMapWebApp.Controllers
{
    public class TopicsController : Controller
    {
        private readonly ITopicRepository _topicRepository;

        public TopicsController(IConfiguration configuration, ITopicRepository topicRepository)
        {
            _topicRepository = topicRepository;

        }

        // GET: Topics
        public async Task<ActionResult> Index()
        {
            IEnumerable<Topic> model = new List<Topic>();
            model = await _topicRepository.GetTopics();

            return View(model);
        }

        // GET: Topics/Details/5
        public async Task<ActionResult> Details(int id)
        {
            Topic topic = await GetTopic(id);

            if (topic == null)
            {
                return new NotFoundResult();
            }

            return View(topic);
        }

        // GET: Topics/Create
        public ActionResult Create()
        {
            // This shouldn't need to talk to the Web API as we're just displaying an in-place default page
            var topic = new Topic();

            return View(topic);
        }

        // POST: Topics/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(IFormCollection collection)
        {

            try
            {
                var topic = new Topic();

                // Copy form values into the new item
                UpdateTopicFromForm(topic, collection);

                await _topicRepository.CreateTopic(topic);

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                throw new Exception("The topic could not be created", ex);
            }
        }

        // GET: Topics/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            Topic topic = await GetTopic(id);

            if (topic == null)
            {
                return new NotFoundResult();
            }

            return View(topic);
        }

        private async Task<Topic> GetTopic(int id)
        {
            var topic = await _topicRepository.GetTopic(id);

            return topic;
        }

        // POST: Topics/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, IFormCollection collection)
        {
            Topic topic = await GetTopic(id);
            if (topic == null)
            {
                return new NotFoundResult();
            }

            try
            {

                // Copy form values into the item
                UpdateTopicFromForm(topic, collection);

                await _topicRepository.UpdateTopic(topic);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(topic);
            }
        }

        // GET: Topics/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var topic = await GetTopic(id);
            if (topic == null)
            {
                return new NotFoundResult();
            }

            return View(topic);
        }

        // POST: Topics/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            if (await _topicRepository.DeleteTopic(id))
            {
                return RedirectToAction(nameof(Index));
            }

            // Let's just show the delete dialog again? Not sure the ideal way to handle this failure.
            return View(await GetTopic(id));
        }
        
        private static void UpdateTopicFromForm(Topic topic, IFormCollection collection)
        {
            topic.Name = collection[nameof(topic.Name)];
            topic.Description = collection[nameof(topic.Description)];
        }

    }
}

MindMapWebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>This is a dummy app themed around notes and mind maps. Don't expect too much. It's all about the tech.</p>

MindMapWebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

MindMapWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="jumbotron margin-top-xs">
    <h1>Mind Map Learning App</h1>
    <p>This is an ASP .NET Core learning application using a Web API and SQL Server database.</p>
    <a asp-area="" asp-controller="Topics" asp-action="Index" class="btn btn-lg btn-primary">View Topics</a>
</div>

MindMapWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mind Map Learning App</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Mind Map</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Topics" asp-action="Index">Topics</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Matt Eland</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

MindMapWebApp/Views/Topics/Create.cshtml
@model MindMapClasses.Models.Topic

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Topic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MindMapWebApp/Views/Topics/Delete.cshtml
@model MindMapClasses.Models.Topic

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Topic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MindMapWebApp/Views/Topics/Details.cshtml
@model MindMapClasses.Models.Topic

@{
    ViewData["Title"] = "Topic Details";
}

<h2>Topic Details</h2>

<div>
    <h4>Topic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TopicType.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TopicType.Name)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

MindMapWebApp/Views/Topics/Edit.cshtml
@model MindMapClasses.Models.Topic

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Topic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MindMapWebApp/Views/Topics/Index.cshtml
@model IEnumerable<MindMapClasses.Models.Topic>

@{
    ViewData["Title"] = "Topics";
}

<h2>Topics</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TopicType.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TopicType.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>